version: '3.1'
networks:
  app_network:
services:
  nginx:
    image: nginx:stable-alpine
    container_name: test-task-two.nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      -   app_network
  php:
    build:
      context: ./
      dockerfile: ./.docker/Dockerfile
    container_name: test-task-two
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    networks:
      -   app_network
  composer:
    image: composer:latest
    container_name: test-task-two.composer
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      -   app_network
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: test-task-two.mysql
    restart: always
    ports:
      - "3308:3306"
    env_file:
      - ".env"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network
volumes:
  db_data: {}
